# data
dataset: jstet/quotes-500k
extra_chars: '.,!?-;:''"'
min_length: 15
max_length: 300
cipher_type: cryptogram
cipher_kwargs:
  seed: 3
  limit_n: 2500
test_cipher_type: cryptogram
test_cipher_kwargs: {}
num_workers: 8
batch_size: 96
test_size: 0.025
loss_mask_punctuation: false
loss_mask_spaces: false
seed: 0

# model
dim: 768
n_head: 12
n_layer: 12
attn_dropout_p: 0.1
resid_dropout_p: 0.1
ffn_dim_multiplier: null
ffn_dropout_p: 0.1
drop_path: 0.1
dynamic_embeddings: false
unique_decoding: true
embedding_n_layer: 0
embedding_n_head: 0
compile_model: false
use_ema: false
ema_decay: 0.999

# training
learning_rate: 1e-4
warmup_steps: 0
max_iterations: 100000
min_learning_rate: 1e-4
lr_scheduler: constant
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
epsilon: 1e-5
epochs: 100
validate: true
val_freq: 1000
drop_last: false
bf16: true

# logging
wandb_enabled: true
wandb_entity: <your-wandb-username>
wandb_project: <your-project-name>
wandb_group: <your-experiment-group>
wandb_notes: ""
wandb_log_freq: 100
log_lr: true
save_freq: 2500
checkpoint_dir: checkpoints/
